language: cpp
sudo: false  # docker VM
git:
  depth: 99999
cache:
  directories:
  - libdeps
matrix:
  include:
  - os: linux
    dist: xenial
    addons:
      apt:
        packages:
          - libusb-dev
          - freeglut3-dev
          - autoconf-archive
          - libsamplerate0-dev
          - libasound2-dev
          - libusb-1.0-0-dev
          - unzip
          - libasound2-dev
          - libxcursor-dev
          - libxrandr-dev
          - libxinerama-dev
          - imagemagick
          - quilt
          - markdown
    env:
      - HOST=""
      - MATRIX_EVAL="echo '--progress=bar:force' >$HOME/.wgetrc"
      - DEPLOY_PAGES="1"
    compiler: gcc
    install:
      - wget -O /tmp/hugo.deb https://github.com/gohugoio/hugo/releases/download/v0.54.0/hugo_0.54.0_Linux-64bit.deb
      - sudo dpkg -i /tmp/hugo.deb
  - os: linux
    dist: xenial
    addons:
      apt:
        sources:
          - ubuntu-toolchain-r-test
        packages:
          - g++-mingw-w64
          - autoconf-archive
          - unzip
          - quilt
          - wine
          - markdown
    env:
      - HOST="x86_64-w64-mingw32"
      - MINGW_ON_LINUX="1"
      - MATRIX_EVAL="unset CC && unset CXX && echo '--progress=bar:force' >$HOME/.wgetrc"
    install:
      - wget -O /tmp/hugo.deb https://github.com/gohugoio/hugo/releases/download/v0.54.0/hugo_0.54.0_Linux-64bit.deb
      - sudo dpkg -i /tmp/hugo.deb
  - os: osx
    osx_image: xcode10
    env: HOST="" MATRIX_EVAL="brew install freeglut autoconf-archive quilt hugo markdown"
    compiler: clang
before_install:
  - eval "${MATRIX_EVAL}"
script:  pwd && echo MINGW_ON_LINUX=$MINGW_ON_LINUX && ./bootstrap.sh && (./autogen.sh --host=$HOST --disable-debug --prefix=$PWD/inst || (cat config.log; false)) && make && make check && make install && source util/travis-deploy.sh
after_script:
- 
# - make distcheck # will not work without re-bootstrapping, wasteful
notifications:
  email:
    recipients:
      - radarsat1@gmail.com
    on_success: never
    on_failure: change
before_deploy:
  # Set up git user name and tag this commit
  - git config --local user.name "Stephen Sinclair"
  - git config --local user.email "radarsat1@gmail.com"
  - export TRAVIS_TAG=nightly-${TRAVIS_PULL_REQUEST_BRANCH:-$TRAVIS_BRANCH}
  - git tag -d $TRAVIS_TAG || echo 'No tag to delete.'
  - git tag $TRAVIS_TAG
deploy:
  - provider: pages
    skip-cleanup: true
    github-token: $GITHUB_TOKEN
    keep-history: true
    on:
      branch: master
      condition: "$DEPLOY_PAGES = 1"
    local-dir: pages
    target-branch: gh-pages
    verbose: true
  - provider: releases
    api_key: $GITHUB_TOKEN
    file: $FILE_TO_UPLOAD
    skip_cleanup: true
    draft: true
    verbose: true
